name: hibiscus
version: 0.1.0.0

extra-source-files:
  - README.md
  - LICENSE

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - Hibiscus.Ast
    - Hibiscus.Parsing.Lexer
    - Hibiscus.Parsing.Parser
    - Hibiscus.CodeGen.Constants
    - Hibiscus.CodeGen.Type.DataType
    - Hibiscus.CodeGen.Types
    - Hibiscus.CodeGen
    - Hibiscus.Asm
    - Hibiscus.TypeInfer
  dependencies:
    - array
    - base
    - bytestring
    - containers
    - mtl
    - transformers
  build-tools:
    - alex
    - happy

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - base
    - bytestring
    - hibiscus

tests:
  simple:
    main: simple.hs
    source-dirs:
      - test
    dependencies:
      - base
      - bytestring
      - hibiscus
  if-then-else:
    main: ifelse.hs
    source-dirs:
      - test
    dependencies:
      - base
      - bytestring
      - hibiscus
