name: hibiscus
version: 0.1.0.0

extra-source-files:
  - README.md
  - LICENSE

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
    - Hibiscus.Ast
    - Hibiscus.Lexer
    - Hibiscus.Parser
    - Hibiscus.Type
    - Hibiscus.CodeGen
    - Hibiscus.Asm
    - Hibiscus.Type2
  dependencies:
    - array
    - base
    - bytestring
    - containers
    - mtl
  build-tools:
    - alex
    - happy

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
    - base
    - bytestring
    - hibiscus

tests:
  type-infer:
    main: typeinfer.hs
    source-dirs:
      - test
      - src
    other-modules:
      - Hibiscus.Ast
      - Hibiscus.Type
    dependencies:
      - base
      - bytestring
      - containers
