name: hibiscus
version: 0.1.0.0

extra-source-files:
- README.md
- LICENSE

default-extensions:
- OverloadedStrings

library:
  source-dirs: src
  exposed-modules:
  - Hibiscus.Ast
  - Hibiscus.Lexer
  - Hibiscus.Parser
  - Hibiscus.Type
  dependencies:
  - array
  - base
  - bytestring
  - containers
  - mtl
  build-tools:
  - alex
  - happy

executable:
  main: Main.hs
  source-dirs: driver
  dependencies:
  - base
  - bytestring
  - hibiscus

tests:
  typeinfer-playground:
    main: type.hs
    source-dirs:
    - test
    dependencies:
    - base
    - hibiscus

